<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #111; }
        .header { border-bottom: 1px solid #ddd; padding-bottom: 8px; margin-bottom: 12px; }
        .h1 { font-size: 18px; font-weight: 700; margin: 0; }
        .meta { color: #555; margin-top: 4px; font-size: 11px; }
        .section { margin-top: 14px; }
        .section h2 { font-size: 14px; margin: 0 0 6px 0; border-bottom: 1px solid #eee; padding-bottom: 4px; }
        .item { border: 1px solid #eee; padding: 8px; border-radius: 6px; margin-bottom: 8px; }
        .muted { color: #666; font-size: 11px; }
        .row { display: flex; justify-content: space-between; gap: 12px; }
        .badge { display: inline-block; padding: 2px 6px; border-radius: 6px; background: #f3f4f6; font-size: 10px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border-bottom: 1px solid #eee; padding: 6px 4px; text-align: left; }
        th { background: #fafafa; }
        .right { text-align: right; }
        .total { font-weight: 700; }
    </style>
</head>
<body>
    <div class="header">
        <div class="h1">{{ $project->name }} — Report</div>
        <div class="meta">
            Period: {{ $from }} to {{ $to }} |
            Generated: {{ $generatedAt }} |
            Generated by: {{ $generatedBy }}
        </div>
        @if($subtitle)
            <div class="meta">{{ $subtitle }}</div>
        @endif
    </div>

    @if($options['include_today_logs'] ?? true)
        <div class="section">
            <h2>Today Logs</h2>
            @forelse($todayLogs as $log)
                <div class="item">
                    <div class="row">
                        <div><strong>{{ $log['user']['name'] }}</strong> <span class="muted">({{ $log['log_date'] }})</span></div>
                        <div class="badge">{{ $log['progress_percent'] ?? '—' }}%</div>
                    </div>
                    <div class="muted">Weather: {{ $log['weather'] ?? '—' }}</div>
                    <div style="margin-top:6px;"><strong>Work done:</strong><br>{!! nl2br(e($log['work_done'] ?? '—')) !!}</div>
                    <div style="margin-top:6px;"><strong>Blockers:</strong><br>{!! nl2br(e($log['blockers'] ?? '—')) !!}</div>
                    <div style="margin-top:6px;"><strong>Next steps:</strong><br>{!! nl2br(e($log['next_steps'] ?? '—')) !!}</div>
                </div>
            @empty
                <div class="muted">No today logs in this period.</div>
            @endforelse
        </div>
    @endif

    @if($options['include_logs'] ?? true)
        <div class="section">
            <h2>Logs Timeline</h2>
            @forelse($logs as $l)
                <div class="item">
                    <div class="row">
                        <div>
                            <strong>{{ $l['title'] ?: '(No title)' }}</strong>
                            <span class="badge">{{ $l['type'] }}</span>
                        </div>
                        <div class="muted">{{ $l['log_date'] }} {{ $l['log_time'] }}</div>
                    </div>
                    <div class="muted">By {{ $l['user']['name'] }}</div>
                    <div style="margin-top:6px;">{!! nl2br(e($l['body'] ?? '—')) !!}</div>
                </div>
            @empty
                <div class="muted">No logs in this period.</div>
            @endforelse
        </div>
    @endif

    @if($options['include_tasks'] ?? true)
        <div class="section">
            <h2>Tasks</h2>
            <table>
                <thead>
                <tr>
                    <th>Title</th>
                    <th>Status</th>
                    <th>Priority</th>
                    <th>Assignee</th>
                    <th>Due</th>
                </tr>
                </thead>
                <tbody>
                @forelse($tasks as $t)
                    <tr>
                        <td>{{ $t['title'] }}</td>
                        <td>{{ $t['status'] }}</td>
                        <td>{{ $t['priority'] }}</td>
                        <td>{{ $t['assignee']['name'] ?? '—' }}</td>
                        <td>{{ $t['due_date'] ?? '—' }}</td>
                    </tr>
                @empty
                    <tr><td colspan="5" class="muted">No tasks.</td></tr>
                @endforelse
                </tbody>
            </table>
        </div>
    @endif

    @if($options['include_issues'] ?? true)
        <div class="section">
            <h2>Issues</h2>
            <table>
                <thead>
                <tr>
                    <th>Title</th>
                    <th>Status</th>
                    <th>Severity</th>
                    <th>Assignee</th>
                    <th>Due</th>
                </tr>
                </thead>
                <tbody>
                @forelse($issues as $i)
                    <tr>
                        <td>{{ $i['title'] }}</td>
                        <td>{{ $i['status'] }}</td>
                        <td>{{ $i['severity'] }}</td>
                        <td>{{ $i['assignee']['name'] ?? '—' }}</td>
                        <td>{{ $i['due_date'] ?? '—' }}</td>
                    </tr>
                @empty
                    <tr><td colspan="5" class="muted">No issues.</td></tr>
                @endforelse
                </tbody>
            </table>
        </div>
    @endif

    @if($options['include_costs'] ?? true)
        <div class="section">
            <h2>Costs</h2>
            <table>
                <thead>
                <tr>
                    <th>Date</th>
                    <th>Category</th>
                    <th>Vendor</th>
                    <th>Description</th>
                    <th class="right">Amount</th>
                </tr>
                </thead>
                <tbody>
                @php $total = 0; @endphp
                @forelse($costs as $c)
                    @php $total += $c['amount']; @endphp
                    <tr>
                        <td>{{ $c['cost_date'] }}</td>
                        <td>{{ $c['category'] }}</td>
                        <td>{{ $c['vendor'] ?? '—' }}</td>
                        <td>{{ $c['description'] ?? '—' }}</td>
                        <td class="right">{{ number_format($c['amount'], 2) }}</td>
                    </tr>
                @empty
                    <tr><td colspan="5" class="muted">No costs.</td></tr>
                @endforelse
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="4" class="right total">Total</td>
                    <td class="right total">{{ number_format($total, 2) }}</td>
                </tr>
                </tfoot>
            </table>
        </div>
    @endif

    <div class="section">
        <h2>Evidence & Attachments</h2>
        
        @if(count($media) > 0)
            <h3>Media</h3>
            <ul>
            @foreach($media as $m)
                <li class="item">
                    <strong>Media #{{ $m['id'] }}</strong>: {{ $m['caption'] ?: 'No caption' }} <span class="muted">({{ $m['created_at'] }})</span>
                </li>
            @endforeach
            </ul>
        @endif

        @if(count($attachments) > 0)
            <h3>Files</h3>
            <table>
                <thead>
                    <tr>
                        <th>File</th>
                        <th>Caption</th>
                        <th>Size</th>
                        <th>Uploaded By</th>
                        <th>Link</th>
                    </tr>
                </thead>
                <tbody>
                @foreach($attachments as $a)
                    <tr>
                        <td>{{ $a['original_name'] }}</td>
                        <td>{{ $a['caption'] ?? '—' }}</td>
                        <td>{{ number_format($a['size'] / 1024, 1) }} KB</td>
                        <td>{{ $a['uploader'] ?? '—' }}</td>
                        <td><a href="{{ $a['url'] }}">Download</a></td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        @endif

        @if(count($media) === 0 && count($attachments) === 0)
            <div class="muted">No attached evidence in this period.</div>
        @endif
    </div>

    <div class="section muted">
        BuildFlow — Simple construction tracking.
    </div>
</body>
</html>
